version: "3.6"

services:
  postgres:
    image: postgis/postgis
    restart: always
    environment:
      POSTGRES_USER: studio-d-admin
      POSTGRES_PASSWORD: studio-password
      POSTGRES_DB: studio-d
    ports:
      - 5432:5432
    volumes:
      - postgresql:/var/lib/postgresql
      - postgis_data:/var/lib/postgresql/data

  maildev:
    image: djfarrelly/maildev
    ports:
      - "1080:80"
      - "25:25"

volumes:
  postgresql:
  postgis_data:
